### PR TITLE
Run suite against celluloid 0.17, 0.18 and master

### PR DESCRIPTION
**Pull request by sobrinho**

### CODE REVIEW

**Comment by blazeroot** [comment]
Hey @sobrinho,

thank you for this PR! I'll merge it after telemetry will be merged, this should fix failed tests and I'll be able to merge it.

**Comment by sobrinho** [comment]
Hey, @blazeroot!

The build is failing but for a problem in Travis (only for jRuby), I opened an [issue](https://github.com/travis-ci/travis-ci/issues/8412) with them.

Running locally is fine.

**Comment by blazeroot** [comment]
Bumping jdk version to 8 works too :-)

**Comment by sobrinho** [comment]
@blazeroot the build is green now, thanks!

**Pull request merged**
