### PR TITLE
fix(delete-messages): fix issue with channel encoding

### PR DESCRIPTION
**Pull request by parfeon**
fix(delete-messages): fix issue with channel encoding

Fix issue because of which channel hasn't been encoded properly with endpoint call.

### CODE REVIEW

**Review by seba-aln — APPROVED** [review]
LGTM

**Comment by parfeon** [comment]
@client-engineering-bot release

**Comment by pn-op** [comment]
🛑 Build failed. Please check release build for details 🛑

**Comment by pn-op** [comment]
🚀 Release successfully completed 🚀

**Pull request merged**
