### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by elioncho**
Update concurrent-ruby and concurrent-ruby-edge dependencies

### CODE REVIEW

**Comment by ascot21** [comment]
What's the status on merging this? Would be great to have concurrent-ruby version updated

**Comment by parfeon** [comment]
On Thursday, we will release with this fix and few more from dependabot

**Comment by ascot21** [comment]
I thought this was being released last week?

**Comment by parfeon** [comment]
@ascot21 it was. Sorry, that not updated the ticket.

**Comment by ascot21** [comment]
@parfeon awesome, thanks!

**Pull request closed without merging**
